### ISSUE TITLE
Drop need for runtime parser.

### ISSUE THREAD

**Issue by jamestalmage** [power-assert-js/espower#24]
We had discussed embedding the entire AST, but I think there might be an even easier way:

```js
  assert(this.ary.indexOf(zero) === two)
              |   |       |     |   |
              |   |       |     |   2
              |   -1      0     false
              [1,2,3]
```

Why not just precompute the offset in the source, and pass that to capture?
Drop the concept of the AST from runtime completely!

```js
assert(assert._expr(
  assert._capt(
    assert._capt(
      assert._capt(this.ary, 12).indexOf(assert._capt(zero, 24)),
      16
    )
    ===
    asert.capt(two, 34),
    30  // <= all these numbers are just the left offset.
  )
));
```

It would mean a lot of rework, but once complete it would make the client super simple.

**Comment by twada** [comment]
Thanks. Precomputing left offsets would be a great idea.

However I want to tell runtime richer node informations (in short, AST).
Not only their locations but types, operators,... because renderers have to know them.

- [succinct-diagram renderer for AVA](https://github.com/twada/power-assert-renderers/blob/master/lib/succinct-diagram.js) uses node types to control output depth.
- [binary-expression renderer](https://github.com/power-assert-js/power-assert-formatter/blob/master/lib/built-in/binary-expression.js) uses types to detect BinaryExpressions and shows unified diff when both sides are strings.

If runtime (formatters / renderers) have much more informations, we can control output more easily.

**Comment by jamestalmage** [comment]
Ah, OK. Got it
